/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as PathsIndexRouteImport } from './routes/paths.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ResourcesRiceCalculatorRouteImport } from './routes/resources.rice-calculator'
import { Route as ResourcesProductKpisRouteImport } from './routes/resources.product-kpis'
import { Route as ResourcesWritingPrdsRouteImport } from './routes/resources.writing-prds'
import { Route as ResourcesRetailPmL2InterviewGuideRouteImport } from './routes/resources.retail-pm-l2-interview-guide'
import { Route as PathsFoundationsRouteImport } from './routes/paths.foundations'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CoursesProductKpisRouteImport } from './routes/courses.product-kpis'
import { Route as CoursesWritingPrdsRouteImport } from './routes/courses.writing-prds'
import { Route as ArticlesOpportunityTreesRouteImport } from './routes/articles.opportunity-trees'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ResourcesRiceCalculatorRoute = ResourcesRiceCalculatorRouteImport.update({
  id: '/rice-calculator',
  path: '/rice-calculator',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesProductKpisRoute = ResourcesProductKpisRouteImport.update({
  id: '/product-kpis',
  path: '/product-kpis',
  getParentRoute: () => ResourcesRoute,
} as any)
const CoursesProductKpisRoute = CoursesProductKpisRouteImport.update({
  id: '/product-kpis',
  path: '/product-kpis',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesWritingPrdsRoute = CoursesWritingPrdsRouteImport.update({
  id: '/writing-prds',
  path: '/writing-prds',
  getParentRoute: () => CoursesRoute,
} as any)
const ResourcesWritingPrdsRoute = ResourcesWritingPrdsRouteImport.update({
  id: '/writing-prds',
  path: '/writing-prds',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesRetailPmL2InterviewGuideRoute =
  ResourcesRetailPmL2InterviewGuideRouteImport.update({
    id: '/retail-pm-l2-interview-guide',
    path: '/retail-pm-l2-interview-guide',
    getParentRoute: () => ResourcesRoute,
  } as any)
const PathsFoundationsRoute = PathsFoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => PathsRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const ArticlesOpportunityTreesRoute =
  ArticlesOpportunityTreesRouteImport.update({
    id: '/opportunity-trees',
    path: '/opportunity-trees',
    getParentRoute: () => ArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/opportunity-trees': typeof ArticlesOpportunityTreesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/product-kpis': typeof CoursesProductKpisRoute
  '/courses/writing-prds': typeof CoursesWritingPrdsRoute
  '/paths/foundations': typeof PathsFoundationsRoute
  '/resources/rice-calculator': typeof ResourcesRiceCalculatorRoute
  '/resources/product-kpis': typeof ResourcesProductKpisRoute
  '/resources/writing-prds': typeof ResourcesWritingPrdsRoute
  '/resources/retail-pm-l2-interview-guide': typeof ResourcesRetailPmL2InterviewGuideRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/opportunity-trees': typeof ArticlesOpportunityTreesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/product-kpis': typeof CoursesProductKpisRoute
  '/courses/writing-prds': typeof CoursesWritingPrdsRoute
  '/paths/foundations': typeof PathsFoundationsRoute
  '/resources/rice-calculator': typeof ResourcesRiceCalculatorRoute
  '/resources/product-kpis': typeof ResourcesProductKpisRoute
  '/resources/writing-prds': typeof ResourcesWritingPrdsRoute
  '/resources/retail-pm-l2-interview-guide': typeof ResourcesRetailPmL2InterviewGuideRoute
  '/articles': typeof ArticlesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/paths': typeof PathsIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/opportunity-trees': typeof ArticlesOpportunityTreesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/product-kpis': typeof CoursesProductKpisRoute
  '/courses/writing-prds': typeof CoursesWritingPrdsRoute
  '/paths/foundations': typeof PathsFoundationsRoute
  '/resources/rice-calculator': typeof ResourcesRiceCalculatorRoute
  '/resources/product-kpis': typeof ResourcesProductKpisRoute
  '/resources/writing-prds': typeof ResourcesWritingPrdsRoute
  '/resources/retail-pm-l2-interview-guide': typeof ResourcesRetailPmL2InterviewGuideRoute
  '/articles/': typeof ArticlesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/courses'
    | '/paths'
    | '/resources'
    | '/sitemap.xml'
    | '/articles/opportunity-trees'
    | '/courses/$slug'
    | '/courses/product-kpis'
    | '/paths/foundations'
    | '/resources/rice-calculator'
    | '/resources/product-kpis'
    | '/resources/retail-pm-l2-interview-guide'
    | '/articles/'
    | '/courses/'
    | '/paths/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/articles/opportunity-trees'
    | '/courses/$slug'
    | '/courses/product-kpis'
    | '/paths/foundations'
    | '/resources/rice-calculator'
    | '/resources/product-kpis'
    | '/resources/retail-pm-l2-interview-guide'
    | '/articles'
    | '/courses'
    | '/paths'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/courses'
    | '/paths'
    | '/resources'
    | '/sitemap.xml'
    | '/articles/opportunity-trees'
    | '/courses/$slug'
    | '/courses/product-kpis'
    | '/paths/foundations'
    | '/resources/rice-calculator'
    | '/resources/product-kpis'
    | '/resources/retail-pm-l2-interview-guide'
    | '/articles/'
    | '/courses/'
    | '/paths/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  PathsRoute: typeof PathsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/paths/': {
      id: '/paths/'
      path: '/'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof PathsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/resources/rice-calculator': {
      id: '/resources/rice-calculator'
      path: '/rice-calculator'
      fullPath: '/resources/rice-calculator'
      preLoaderRoute: typeof ResourcesRiceCalculatorRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/product-kpis': {
      id: '/resources/product-kpis'
      path: '/product-kpis'
      fullPath: '/resources/product-kpis'
      preLoaderRoute: typeof ResourcesProductKpisRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/writing-prds': {
      id: '/resources/writing-prds'
      path: '/writing-prds'
      fullPath: '/resources/writing-prds'
      preLoaderRoute: typeof ResourcesWritingPrdsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/retail-pm-l2-interview-guide': {
      id: '/resources/retail-pm-l2-interview-guide'
      path: '/retail-pm-l2-interview-guide'
      fullPath: '/resources/retail-pm-l2-interview-guide'
      preLoaderRoute: typeof ResourcesRetailPmL2InterviewGuideRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/paths/foundations': {
      id: '/paths/foundations'
      path: '/foundations'
      fullPath: '/paths/foundations'
      preLoaderRoute: typeof PathsFoundationsRouteImport
      parentRoute: typeof PathsRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/product-kpis': {
      id: '/courses/product-kpis'
      path: '/product-kpis'
      fullPath: '/courses/product-kpis'
      preLoaderRoute: typeof CoursesProductKpisRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/writing-prds': {
      id: '/courses/writing-prds'
      path: '/writing-prds'
      fullPath: '/courses/writing-prds'
      preLoaderRoute: typeof CoursesWritingPrdsRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/articles/opportunity-trees': {
      id: '/articles/opportunity-trees'
      path: '/opportunity-trees'
      fullPath: '/articles/opportunity-trees'
      preLoaderRoute: typeof ArticlesOpportunityTreesRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesOpportunityTreesRoute: typeof ArticlesOpportunityTreesRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesOpportunityTreesRoute: ArticlesOpportunityTreesRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesProductKpisRoute: typeof CoursesProductKpisRoute
  CoursesWritingPrdsRoute: typeof CoursesWritingPrdsRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesProductKpisRoute: CoursesProductKpisRoute,
  CoursesWritingPrdsRoute: CoursesWritingPrdsRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface PathsRouteChildren {
  PathsFoundationsRoute: typeof PathsFoundationsRoute
  PathsIndexRoute: typeof PathsIndexRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsFoundationsRoute: PathsFoundationsRoute,
  PathsIndexRoute: PathsIndexRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesRiceCalculatorRoute: typeof ResourcesRiceCalculatorRoute
  ResourcesProductKpisRoute: typeof ResourcesProductKpisRoute
  ResourcesWritingPrdsRoute: typeof ResourcesWritingPrdsRoute
  ResourcesRetailPmL2InterviewGuideRoute: typeof ResourcesRetailPmL2InterviewGuideRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesRiceCalculatorRoute: ResourcesRiceCalculatorRoute,
  ResourcesProductKpisRoute: ResourcesProductKpisRoute,
  ResourcesWritingPrdsRoute: ResourcesWritingPrdsRoute,
  ResourcesRetailPmL2InterviewGuideRoute: ResourcesRetailPmL2InterviewGuideRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  PathsRoute: PathsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
